### ISSUE TITLE
Add support for geologging files

### ISSUE THREAD

**Issue by justinlewis** [terraframe/osmre-uav#189]
Geologging for Sony cameras, such as the RX1R, need to be supported.

Desired Behavior:

1. Add a checkbox to the frone-end on upload and reprocessing such that the user can select to use the geo location file when processing in ODM

**Comment by jsmethie** [comment]
Extra information about surveying a location with a Sony RX1R camera (which does not have GPS):
https://event38.com/wp-content/uploads/2022/06/PPK-surveying-with-the-E400-and-Sony-RX1R-II.pdf
