### ISSUE TITLE
Expand metadata to support more of the USGS USA Data Delivery spec

### ISSUE THREAD

**Issue by justinlewis** [terraframe/osmre-uav#190]
[USGS USA Data Delivery spec](https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/atoms/files/USGS%20UAS%20Data%20Delivery%20Spec1.4_042021.pdf)

Adopt and integrate metadata standards for products defined in USGS UAS Data Delivery spec. These include currently established metadata standards for raw imagery, point clouds, DTMs and orthorectified imagery.

**Comment by jsmethie** [comment]
Its possible we can use a tool like exiftool to exif-tags from a tiff if they exist.  Can that be used to determine some of the metadata or will the user need to manually enter that information?

**Comment by justinlewis** [comment]
This ticket is specifically targeting metadata for products. The spec has an initial schema defined:

```
<Upload>
 <dataType>raw</dataType>
 <accessibleSupportType/>
 <inaccessibleSupportType/>
 <orthoStartDate/>
 <orthoEndDate/>
 <orthoCorrectionModel/>
 <ptCloudEpsgNumber/>
 <ptCloudStartDate/>
 <ptCloudEndDate/>
 <rawFocalLength>23</rawFocalLength>
 </Upload>
```

TODO: determine if there are more properties needed for the different product types.
