### ISSUE TITLE
Improve error messages for failed processing jobs

### ISSUE THREAD

**Issue by justinlewis** [terraframe/osmre-uav#191]

**Comment by justinlewis** [comment]
https://github.com/terraframe/osmre-uav/issues/235

**Comment by rrowlands** [comment]
Try to collect error messages such as "Invalid route for taskId efaebddc-4456-4385-9c69-b386771d3d19:info, no task table entry." as a "connection with ODM failed"

Also "Cannot process dataset" -> "Cannot process dataset, view the ODM output for more information".
