### ISSUE TITLE
Cannot process MicaSense multispectral imagery.

### ISSUE THREAD

**Issue by justinlewis** [terraframe/osmre-uav#195]
Cannot process MicaSense multispectral imagery.  MicaSense RedEdge-MX and Altum are identified as supported sensors, but these data cannot be processed. Can only be stored in IDM.

Need capability to process multispectral imagery for MicaSense (e.g., RedEdge-MX, Altum, RedEdge-P camera).

**Comment by rrowlands** [comment]
Multispectral processing is now handled via ODM.
