### ISSUE TITLE
Ability for user to set to native resolution or a different resolution of ODM runs

### ISSUE THREAD

**Issue by justinlewis** [terraframe/osmre-uav#200]

**Comment by jsmethie** [comment]
ODM supports multiple resolution parameters:
`[orthophoto-resolution](https://docs.opendronemap.org/arguments/orthophoto-resolution/#orthophoto-resolution) <float > 0.0>

    Orthophoto resolution in cm / pixel. Note that this value is capped by a ground sampling distance (GSD) estimate. To remove the cap, check –ignore-gsd also. Default: 5`

`[dem-resolution](https://docs.opendronemap.org/arguments/dem-resolution/#dem-resolution) <float>

    DSM/DTM resolution in cm / pixel. Note that this value is capped to 2x the ground sampling distance (GSD) estimate. To remove the cap, check –ignore-gsd also. Default: 5`

Do we want to support both or only one of them?
