### ISSUE TITLE
Add ability for non-admins to add new platforms and sensors

### ISSUE THREAD

**Issue by justinlewis** [terraframe/osmre-uav#202]
Issue: Inability to add additional platforms and/or sensors (understand the reason to preserve this capability to very limited number of people to ensure accuracy of entry and ease of use for all users.

Solution: In addition to IDM admin ability to add new platforms and sensors, grant admin privileges to select FS staff to do so as well.

**Comment by jsmethie** [comment]
Do we need another tier of users or is this just making additional users be admins?
