### ISSUE TITLE
Encountering Max Runtime Exception Throws Weird Error

### ISSUE THREAD

**Issue by rrowlands** [terraframe/osmre-uav#235]
Currently, the processing limit for collections is set to three days. If this limit is reached, the following error is presented to the user:

Proxy redirect error: connect ECONNREFUSED 10.120.10.119:3000

Which doesn't at all tell them what went wrong. This error message should be replaced with something more useful, i.e. "Max runtime limit exceeded (3 days)", and we can perhaps consider increasing it to a week?

**Comment by justinlewis** [comment]
Closing as I believe this was completed.
