### ISSUE TITLE
Improvements to loading indicators

### ISSUE THREAD

**Issue by justinlewis** [terraframe/osmre-uav#236]
- [ ] Move collection modal loading spinner (when clicking next buttons) from the button section to the general modal so that the entire modal is disabled
- [ ] Consolidate loading spinner to a single style. Currently there are four. The "Loading application data..." on app load, the original (click "get info" on a product), and the collection modal when clicking next, and when expanding a workflow task.
- [ ] Add spinner to collection modal when clicking between tabs

**Comment by jsmethie** [comment]
The "Loading application data..." spinner isn't something that can use existing .css or angular components.  That spinner is displayed when angular is bootstrapping itself on page load.  If we want to re-use an existing component then it will need to be duplicated and hard-coded into the per-boostrapped page definition

**Comment by justinlewis** [comment]
I think if we just make the font size smaller for the app loading page that will be better.
