### ISSUE TITLE
Add focal length to metadata registration and xml specification

### ISSUE THREAD

**Issue by justinlewis** [terraframe/osmre-uav#238]
Focal length is a part of "upload" group on the [Data Delivery Specification](https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/atoms/files/USGS%20UAS%20Data%20Delivery%20Spec1.4_042021.pdf). 

This needs to be added to the sensor metadata registration process.

**Comment by rrowlands** [comment]
Does existing data need to be patched?

**Comment by justinlewis** [comment]
No it doesn't
