### ISSUE TITLE
Collection Date Saves as Day Before

### ISSUE THREAD

**Issue by justinlewis** [terraframe/osmre-uav#373]
I'm reporting this ticket for someone else. 

---------- Original message below ---------

I am reaching out on behalf of a Forest Service employee who has noticed an issue with the Collection Date parameter when creating Collections. It appears that after entering a date and saving the Collection, the date that’s saved is one day earlier than what was inputted. Are you familiar with this issue? Is the date parameter in a different time zone that’s causing it to appear as previous day when converted to the user’s local time zone?
 
I’ve tested this myself and found the same issue.

![Image](https://github.com/terraframe/osmre-uav/assets/2043001/539b3256-648e-4c05-b9ed-3663044b51ad)

![Image](https://github.com/terraframe/osmre-uav/assets/2043001/472cda6f-f0f9-4966-933b-191cf32cf20b)

**Comment by jsmethie** [comment]
The date is stored correctly, it is displayed incorrectly on the collection details modal:
![Screenshot from 2024-05-16 09-23-04](https://github.com/terraframe/osmre-uav/assets/240481/c32d4105-534d-4c90-83c9-ce1e5a46bb62)
